Script started on Wed 02 Apr 2025 10:32:49 PM PDT
]0;student@student-VirtualBox: ~/lab10[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab10[00m$ exitscript lab10c-12002.scriptb-12002.script./lab10a lab10data/lab10-12002.iniexit[K./lab10a lab10data/lab10-12000.iniexit[K./lab10a lab10data/lab10-12002.iniexit[Krm lab10c-12000.script lab10c-12002.script laab10c-12004.script lab10d-12012.script[Aexit[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C./lab10a lab10data/lab10-12000.iniexit[Kmore lab10data/*.log./lab10a lab10data/lab10-12012.iniexit[K./lab10a lab10data/lab10-12004.ini
:12004> neighbors
Active connections of :12004:
	:12002,	:12012,
:12004> neighbors
Active connections of :12004:
	:12012,
:12004> neighbors
Active connections of :12004:
	:12012,	:12002,
:12004> quit
]0;student@student-VirtualBox: ~/lab10[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab10[00m$ exit
exit

Script done on Wed 02 Apr 2025 10:35:23 PM PDT
