Script started on Fri 24 Jan 2025 12:33:56 AM PST
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ make l[Kl[Kclean
rm -f lab2a lab2b *.o
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ make lab2b
g++ -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\" -o lab2b lab2b.cpp
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ ./lab2b 0 lab2data/graph1.txt
level 0: 0
level 1: 2
level 1: 1
level 2: 3
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ ./lab2b 0 lab2data/graph1.txt[1P lab2data/graph1.txt2 lab2data/graph1.txt[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P.txt2.txt[C[C[C[C
level 0: 2
level 1: 1
level 1: 3
level 1: 0
level 2: 5
level 2: 4
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ ./lab2b 2 lab2data/graph2.txt[C[C[1P.txt3.txt[1P lab2data/graph3.txt4 lab2data/graph3.txt
level 0: 4
level 1: 5
level 1: 3
level 2: 1
level 2: 2
level 2: 0
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ make clean
rm -f lab2a lab2b *.o
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ exit
exit

Script done on Fri 24 Jan 2025 12:35:52 AM PST
