Script started on Sat 18 Jan 2025 06:52:42 PM PST
]0;student@student-VirtualBox: ~/lab1[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab1[00m$ tcsh
[4mstudent-VirtualBox[24m:[1m~/lab1[0m> make clean
rm -f lab1b lab1c lab1d *.o
[4mstudent-VirtualBox[24m:[1m~/lab1[0m> make lab1d
g++ -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\" -o lab1d lab1d.cpp
[4mstudent-VirtualBox[24m:[1m~/lab1[0m> foreach f (Makefile *c[K.c* *.h*)
foreach? echo "== $f +[K==="=[1@== $f ==="
foreach? ,/l[K[K[K./lab1d $f
foreach? echo -n "wc: "
foreach? wc -l $f
foreach? end
=== Makefile ===
54
0
16
33
0
16
33
0
16
33
0
6
28
number of lines read: 13
wc: 13 Makefile
=== lab1b.cpp ===
38
19
18
17
0
20
4
33
21
22
18
0
35
18
19
19
18
18
19
19
0
35
45
0
32
1
62
57
0
35
13
1
0
number of lines read: 33
wc: 33 lab1b.cpp
=== lab1c.cpp ===
38
19
18
18
17
0
20
4
33
21
22
18
0
35
18
19
19
18
18
19
19
0
35
45
0
32
1
52
0
16
18
0
17
46
0
23
12
6
0
35
0
13
5
0
54
0
35
0
13
1
number of lines read: 50
wc: 49 lab1c.cpp
=== lab1d.cpp ===
38
19
18
17
0
20
4
33
21
22
18
23
0
35
18
19
19
18
18
19
19
0
35
45
0
37
1
15
13
16
0
11
36
23
24
13
4
15
31
29
10
11
12
10
21
11
5
4
3
11
13
2
32
1
34
0
48
17
10
2
0
15
0
11
17
38
15
6
38
100
51
45
16
42
0
9
14
2
43
51
0
53
0
10
1
number of lines read: 85
wc: 85 lab1d.cpp
[4mstudent-VirtualBox[24m:[1m~/lab1[0m> make clean
rm -f lab1b lab1c lab1d *.o
[4mstudent-VirtualBox[24m:[1m~/lab1[0m> exit
exit
]0;student@student-VirtualBox: ~/lab1[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab1[00m$ exit
exit

Script done on Sat 18 Jan 2025 06:54:34 PM PST
