Script started on Wed 02 Apr 2025 10:32:43 PM PDT
]0;student@student-VirtualBox: ~/lab10[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab10[00m$ exitscript lab10c-12002.scriptb-12002.script./lab10a lab10data/lab10-12002.ini
:12002> neighbors
Active connections of :12002:
	:12000,	:12004,	:12012,
:12002> quit
]0;student@student-VirtualBox: ~/lab10[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab10[00m$ ./lab10a lab10data/lab10-12002.ini
:12002> neighbors
Active connections of :12002:
	:12000,	:12004,	:12012,
:12002> quit
]0;student@student-VirtualBox: ~/lab10[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab10[00m$ exot
No command 'exot' found, did you mean:
 Command 'emot' from package 'ruby-emot' (universe)
exot: command not found
]0;student@student-VirtualBox: ~/lab10[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab10[00m$ exit
exit

Script done on Wed 02 Apr 2025 10:35:19 PM PDT
