Script started on Thu 23 Jan 2025 10:38:37 PM PST
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ uname -a
Linux student-VirtualBox 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:26:57 UTC 2021 i686 i686 i686 GNU/Linux
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ make clean
rm -f lab2a *.o
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ make lab2a
g++ -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\" -o lab2a lab2a.cpp
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ [K]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ ./lab2a lab2data/graph1.txt
neighbors of node 0: 2 1 
neighbors of node 1: 3 2 0 
neighbors of node 2: 0 1 3 
neighbors of node 3: 1 2 
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ ./lab2a lab2data/graph1.txt[1P.txt2.txt
neighbors of node 0: 5 3 2 
neighbors of node 1: 2 3 5 4 
neighbors of node 2: 1 3 0 
neighbors of node 3: 1 2 5 0 
neighbors of node 4: 1 5 
neighbors of node 5: 1 3 4 0 
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ ./lab2a lab2data/graph2.txt[1P.txt3.txt
neighbors of node 0: 1 5 2 3 
neighbors of node 1: 2 5 0 
neighbors of node 2: 1 5 0 
neighbors of node 3: 5 0 4 
neighbors of node 4: 5 3 
neighbors of node 5: 1 4 2 0 3 
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ make clean
rm -f lab2a *.o
]0;student@student-VirtualBox: ~/lab2[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab2[00m$ exit
exit

Script done on Thu 23 Jan 2025 10:40:26 PM PST
