Script started on Fri 31 Jan 2025 11:35:41 PM PST
]0;student@student-VirtualBox: ~/lab3[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab3[00m$ ./echo-client 12345
echo-client at 127.0.0.1:56732 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: Hello World!
13 bytes sent from 127.0.0.1:56732
13 bytes received, see next line for data...
Hello World!
]0;student@student-VirtualBox: ~/lab3[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab3[00m$ ./echo-client 12345
echo-client at 127.0.0.1:56734 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: Good-bye for now.
18 bytes sent from 127.0.0.1:56734
18 bytes received, see next line for data...
Good-bye for now.
]0;student@student-VirtualBox: ~/lab3[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab3[00m$ ./echo-client 12345
echo-client at 127.0.0.1:56736 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: 
]0;student@student-VirtualBox: ~/lab3[01;32mstudent@student-VirtualBox[00m:[01;34m~/lab3[00m$ exit
exit

Script done on Fri 31 Jan 2025 11:37:36 PM PST
